language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.302
script:
  - dotnet restore
  - dotnet test ./test/Qwack.Dates.Tests
  - dotnet test ./test/Qwack.Math.Tests
  - dotnet test ./test/Qwack.Core.Tests
